echo '--- Start Script ---'

echo $(date -u) 'Start'

python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_1'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_2'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_3'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_4'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_5'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_6'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_7'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_8'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_9'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_10'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_11'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_12'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_13'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_14'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_15'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_16'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_17'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_18'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_19'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_20'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_21'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_22'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_23'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_24'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_25'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_26'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_27'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_28'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_29'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_30'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_31'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_32'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_33'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_34'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_35'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_36'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_37'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_38'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_39'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_40'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_41'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_42'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_43'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_44'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_45'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_46'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_47'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_48'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_49'
python og_code_yanzhang.py --model 'lora' --size_T 400 --iterations 50 --epochs_sur 4 --epochs_opt 3 --batch_size 120 --lambda_penalty 0.5 --epsilon 1e-5 --file_name 'run_50'



echo $(date -u) 'Finish

